version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST=${V2RAY_HOST}
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy
    restart: always
    
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment:
      - TZ=Asia/Shanghai
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy
    restart: always
    
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
      - VIRTUAL_PORT=1080
      - VIRTUAL_HOST=${V2RAY_HOST}
      - LETSENCRYPT_HOST=${V2RAY_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
      - HSTS=off
      - LETSENCRYPT_TEST=true
      - HTTPS_METHOD=redirect
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
      - /var/log/v2ray:/var/log/v2ray
    expose:
      - "1080"
    networks:
      - nginx-proxy
    restart: always
  
  qrencode:
    image: bxggs/qrencode:latest
    container_name: qrencode
    command: -t utf8 -o - ${VMESS_LINK:-}
    networks:
      - nginx-proxy

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  nginx-proxy:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
